"""user picture number

Revision ID: 4798e126ace5
Revises: 82605bcfa17a
Create Date: 2025-12-20 19:17:22.945714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4798e126ace5'
down_revision: Union[str, Sequence[str], None] = '82605bcfa17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_fts'), table_name='tracks', postgresql_using='gin')
    op.create_index('ix_tracks_fts', 'tracks', [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracks_fts', table_name='tracks', postgresql_using='gin')
    op.create_index(op.f('ix_tracks_fts'), 'tracks', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(author, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
