"""fixxxx

Revision ID: 67b0e3b16a9a
Revises:
Create Date: 2025-12-06 22:39:06.657248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67b0e3b16a9a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- ВСТАВЬ ВОТ ЭТУ СТРОКУ ---
    op.execute("DROP TYPE IF EXISTS musicplatform CASCADE")
    # -----------------------------

    # Дальше пошел старый код, который там уже был:
    # op.create_table('tracks', ...


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reactions")
    op.drop_table("shared_tracks")
    op.drop_table("friendship")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_author"), table_name="tracks")
    op.drop_table("tracks")
    # ### end Alembic commands ###
