"""fixxxx

Revision ID: 67b0e3b16a9a
Revises:
Create Date: 2025-12-06 22:39:06.657248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67b0e3b16a9a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("album_cover_url", sa.String(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum("SPOTIFY", "YANDEX", "APPLE", "VK", "OTHER", name="musicplatform"),
            nullable=False,
        ),
        sa.Column("external_link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracks_author"), "tracks", ["author"], unique=False)
    op.create_index(op.f("ix_tracks_title"), "tracks", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("hashed_password", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(length=15), nullable=True),
        sa.Column("phone_number", sa.String(length=12), nullable=True),
        sa.Column("profile_picture_url", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "friendship",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="friendship_status_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shared_tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shared_track_id", sa.UUID(), nullable=False),
        sa.Column("emoji", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["shared_track_id"],
            ["shared_tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reactions")
    op.drop_table("shared_tracks")
    op.drop_table("friendship")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_author"), table_name="tracks")
    op.drop_table("tracks")
    # ### end Alembic commands ###
