"""changes

Revision ID: 82605bcfa17a
Revises: 8f95f76e2e51
Create Date: 2025-12-17 22:54:34.500855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82605bcfa17a"
down_revision: Union[str, Sequence[str], None] = "8f95f76e2e51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_fts"), table_name="tracks", postgresql_using="gin")
    op.create_index(
        "ix_tracks_fts",
        "tracks",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.execute(
        "UPDATE users SET user_picture_number = 1 WHERE user_picture_number IS NULL"
    )
    op.alter_column(
        "users", "user_picture_number", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "user_picture_number", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index("ix_tracks_fts", table_name="tracks", postgresql_using="gin")
    op.create_index(
        op.f("ix_tracks_fts"),
        "tracks",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(author, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
