"""add gin index real

Revision ID: 8a9a93dbcf23
Revises: 8c6af7682b31
Create Date: 2025-12-12 22:47:57.666532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a9a93dbcf23"
down_revision: Union[str, Sequence[str], None] = "8c6af7682b31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tracks_title_author_gin"),
        table_name="tracks",
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        "ix_tracks_fts",
        "tracks",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_tracks_trgm",
        "tracks",
        ["title", "author"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.drop_index(
        "ix_tracks_trgm",
        table_name="tracks",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
    )
    op.drop_index("ix_tracks_fts", table_name="tracks", postgresql_using="gin")
    op.create_index(
        op.f("ix_tracks_title_author_gin"),
        "tracks",
        ["title", "author"],
        unique=False,
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
