"""add gin index real

Revision ID: 8c6af7682b31
Revises: bf4c970f8c65
Create Date: 2025-12-12 21:06:07.619885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c6af7682b31"
down_revision: Union[str, Sequence[str], None] = "bf4c970f8c65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_tracks_title_author_gin",
        "tracks",
        ["title", "author"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.drop_index(
        "ix_tracks_title_author_gin",
        table_name="tracks",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops", "author": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
