"""empty message

Revision ID: 8f95f76e2e51
Revises: 647b8bb3d005
Create Date: 2025-12-17 15:48:52.080870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f95f76e2e51"
down_revision: Union[str, Sequence[str], None] = "647b8bb3d005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_fts"), table_name="tracks", postgresql_using="gin")
    op.create_index(
        "ix_tracks_fts",
        "tracks",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(author, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column("users", sa.Column("user_picture_number", sa.Integer(), default=1))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.drop_column("users", "user_picture_number")
    op.drop_index("ix_tracks_fts", table_name="tracks", postgresql_using="gin")
    op.create_index(
        op.f("ix_tracks_fts"),
        "tracks",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(author, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
